name: Build Android APK

on:
  push:
    branches: [ "develop", "main", "master" ]
  workflow_dispatch: # Tombol ajaib agar kamu bisa merakit APK secara manual kapan saja

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Mengambil kode dari repository
      uses: actions/checkout@v4

    - name: Menyiapkan Java (JDK 11)
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Memberikan izin akses untuk Gradle
      run: chmod +x gradlew

    - name: Merakit (Build) Aplikasi menjadi APK
      run: ./gradlew assembleDebug

    - name: Menyimpan hasil APK agar bisa di-download
      uses: actions/upload-artifact@v4
      with:
        name: Aplikasi-Notifikasi-Ku
        path: app/build/outputs/apk/debug/*.apk
